version: '3.5'

services:
  random_postgres:
    container_name: random_postgres
    image: postgres:9.6
    environment:
      - POSTGRES_DB=enc
      - POSTGRES_USER=enc
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    ports:
      - "5435:5432"

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
